server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/award?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  elasticsearch:
    host: http://localhost:9200
    allowedIpAddress: localhost
    apiKey: ${ELASTICSEARCH_API_KEY}
  ai:
    dashscope:
      api-key:
        ${DASH_SCOPE_API_KEY}
      text-embeddingModel:
        text-embedding-v4
      chatVLModel:
        qwen3-vl-flash
      chatModel:
        qwen-flash


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.com.code.certificateProcessor.pojo

rocketmq:
  name-server: localhost:9876


aliyun:
  oss:
    endpoint: oss-cn-fuzhou.aliyuncs.com
    accessKeyId: ${ALIYUN_OSS_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
    bucketName: sk8erboi
    bucketDomain: ${ALIYUN_OSS_BUCKET_DOMAIN}


app:
  jwt:
    secret: ${JWT_SECRET}
  url: localhost
